name: Organization Issue
description: Create an issue for the organization
title: "✔️"
body:
- type: checkboxes
  attributes:
    label: I have done the items below . . .
    description: Please make sure to do the items below.
    options:
    - label: I have created a title but left the ✔️ emoji behind.
      required: true

- type: textarea
  attributes:
    label: Description
    description: |
      A description of the task to perform.
      💡Organizational issues are not related to changing code.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      The list of items that need to be finished to satisfy the definition of done.
    value: |
      **This issue is finished when:**
      - [ ] Item 1
      - [ ] Item 2
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: Perform Release To Do List
    description: Complete the following items to perform a release.
    options:
    - label: |
        Add the appropriate labels to this issue template based on the issues being released
        | col 1 | col2 |
        |-------|------|
        | row 2 | row 2 |
    - label: QA Testing finished and all tests pass.
    - label: Branch used for release has been checked out locally and all unit tests have passed.
    - label: Version in project file updated.  (Update <Version/> and <FileVersion/> tags)
    - label: Release notes created and added to the correct release branch.
    - label: The release displayed in [GitHub Releases](https://github.com/KinsonDigital/Velaptor/releases) has been verified to be correct.


- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      No Issue Dependencies
      Example:
        - #10 Item 3
        - #20 Item 4
    description: |
      A list of issues that are dependencies of this issue and need to be completed first.
      Use the '#\<issue-number\>' syntax to link to an issue
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      No Related Work Items Added
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues related to this issue that is not a dependency.
      Use the '#\<issue-number\>' syntax to link to an issue
  validations:
    required: false
