name: 🚧 Project Item
description: Create an issue for a project.  (Project maintainers only)
title: "🚧<title>"
body:
- type: checkboxes
  attributes:
    label: I have done the items below . . .
    description: Please make sure to do the items below.
    options:
    - label: I have updated the title by replacing the '**_\<title\>_**' section.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of feature/change in the user's perspective
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: |
      The list of items and checkboxes of things that need to be finished for the definition of done.
      Add more items as needed . . .
    value: |
      **This issue is finished when:**
      - [ ] Code documentation added if required
      - [ ] Unit tests added
      - [ ] All unit tests pass
  validations:
    required: true
    render: markdown

- type: checkboxes
  attributes:
    label: ToDo Items
    description: Complete the following items before asking for a PR review
    options:
    - label: Draft pull request created and linked to this issue
    - label: Priority label added to issue.  Refer to _**Change Type Labels**_ section below.
    - label: Issue linked to the proper project
    - label: Issue linked to proper milestone

- type: textarea
  attributes:
    label: "Additional information below:"
    description: DO NOT CHANGE ANYTHING BELOW!!
    value: |
      **_<details closed><summary>Change Type Labels</summary>_**
      
      | Change Type         | Label                                                                                |
      |---------------------|--------------------------------------------------------------------------------------|
      | Bug Fixes           | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%90%9Bbug                     |
      | Breaking Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%92%A3breaking%20changes      |
      | Enhancement         | https://github.com/KinsonDigital/Velaptor/labels/enhancement                         |
      | Workflow Changes    | https://github.com/KinsonDigital/Velaptor/labels/workflow                            |
      | Code Doc Changes    | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%91documentation%2Fcode    |
      | Product Doc Changes | https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
      </details>

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      No Issue Dependencies
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues that are dependencies of this issue and need to be finishes first
      Use the '#\<number\>' syntax to link to an issue
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      No Related Work Items Added
      Example:
        - #10 Create new class
        - #20 Add unit tests to service
        - #30 Cleanup code in UI
    description: |
      A list of issues that are related to this issue but that is not a dependency
      Use the '#\<number\>' syntax to link to an issue
  validations:
    required: false

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../code_of_conduct.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
