name: NET GitHub Action Sample

on:
  workflow_dispatch:

jobs:
  Run_Action_Sample:
    name: Run Action Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Print Message
      id: print-message
      uses: KinsonDigital/NETGitHubActionSample@v1.0.0
      with:
        message: "Helle GitHub Actions!!"
