name: NET GitHub Action Sample

on:
  workflow_dispatch:

jobs:
  Run_Action_Sample:
    name: Run Action Sample
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Print Stuff
      id: print-stuff
      shell: pwsh
      run: |
        Write-Output "::notice::omg notice"
        Write-Output "::warning ::omg warning"
        Write-Output "::error   ::omg error"

        ::group::My Group
        This is a message,
        that is grouped,
        and is pretty cool.
        ::endgroup::


# Write-Output "::notice file=notice.js,line=10,endLine={endLine},title=Test Notice::omg notice"
# Write-Output "::warning file=app.js,line=30,title=Test Warning::omg warning"
# Write-Output "::error file={name},line=20,endLine={endLine},title=Test Error::omg error"